/**
 * Midgard Public API
 * The Midgard Public API queries THORChain and any chains linked via the Bifröst and prepares information about the network to be readily available for public users. The API parses transaction event data from THORChain and stores them in a time-series database to make time-dependent queries easy. Midgard does not hold critical information. To interact with BEPSwap and Asgardex, users should query THORChain directly.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: devs@thorchain.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Asset } from './asset';

// export interface StakersAssetData {
//     asset?: Asset;
//     /**
//      * Represents ownership of a pool.
//      */
//     units?: string;
//     dateFirstStaked?: number;
//     heightLastStaked?: number;
// }

export interface StakersAssetData {
    /**
     *
     * @type {string}
     * @memberof StakersAssetData
     */
    asset?: string;
    /**
     * Total of assets staked
     * @type {string}
     * @memberof StakersAssetData
     */
    assetStaked?: string;
    /**
     * Total of assets withdrawn
     * @type {string}
     * @memberof StakersAssetData
     */
    assetWithdrawn?: string;
    /**
     *
     * @type {number}
     * @memberof StakersAssetData
     */
    dateFirstStaked?: number;
    /**
     *
     * @type {number}
     * @memberof StakersAssetData
     */
    heightLastStaked?: number;
    /**
     * Total of rune staked
     * @type {string}
     * @memberof StakersAssetData
     */
    runeStaked?: string;
    /**
     * Total of rune withdrawn
     * @type {string}
     * @memberof StakersAssetData
     */
    runeWithdrawn?: string;
    /**
     * Represents ownership of a pool.
     * @type {string}
     * @memberof StakersAssetData
     */
    units?: string;
}
